### ISSUE TITLE
TypeScript error in generated files

### ISSUE THREAD

**Issue by remisture** [cyclosproject/ng-swagger-gen#27] opened 2018-01-11 08:29 UTC
Any idea what this can be?

> webpack: Compiled successfully.
> ERROR in src/app/services/swagger-generated-ngx/models/custom-attribute-data.ts(10,16): error TS1005: '(' expected.
> src/app/api/models/custom-attribute-data.ts(10,17): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.

**custom-attribute-data.ts:**
```
/* tslint:disable */
import { ConstructorInfo } from './constructor-info';
import { CustomAttributeTypedArgument } from './custom-attribute-typed-argument';
import { CustomAttributeNamedArgument } from './custom-attribute-named-argument';

/**
 */
export class CustomAttributeData {
    attributeType?: string;
    constructor?: ConstructorInfo;
    constructorArguments?: CustomAttributeTypedArgument[];
    namedArguments?: CustomAttributeNamedArgument[];
}
```

**Comment by remisture** [comment] 2018-01-11 08:36
Exporting as interface instead of class seems to fix this problem, ref. #25 

**object.mustache:**

```
{{{modelComments}}}
export interface {{modelClass}} {{#modelParent}}extends {{modelName}} {{/modelParent}}{
  {{#modelProperties}}
    {{propertyName}}{{^propertyRequired}}?{{/propertyRequired}}: {{propertyType}};
  {{/modelProperties}}
}
```

**Comment by luisfpg** [comment] 2018-01-11 14:47
The problem is that **constructor** is a reserved word in typescript, and is used here as property name.
As the workaround for #25 works, and it is on the near road map (but we're in summer holidays period in Brazil, and I'm quite busy in other tasks), there is nothing to do in this issue.
Because if we would generate the property with another name (for example, with a list of reserved words), that would conflict with the object itself being returned / sent from / to the server.
So, I'll close this issue.

**Closed by luisfpg** 2018-01-11 14:47 UTC
