### ISSUE TITLE
Feature request: format date-time

### ISSUE THREAD

**Issue by letsgetswifty** [cyclosproject/ng-swagger-gen#103] opened 2018-09-28 09:26 UTC
Currently dates get always generated as string.

**For example:**
```
"MyDate": {
          "format": "date-time",
          "type": "string",
          "x-nullable": false
        }
```
gets generated as `MyDate: string` instead of `MyDate: Date`

Would it be possible to set datatype Date instead of string?

Something like that would be neccessary:
```
case 'string':
      if(property.format == 'date-time'){
        return 'Date';
      }
      return 'string';
```

**Comment by luisfpg** [comment] 2018-09-28 11:12
Duplicate of https://github.com/cyclosproject/ng-swagger-gen/issues/36

**Closed by luisfpg** 2018-09-28 11:12 UTC
Labels: duplicate
