### ISSUE TITLE
snake casing handling in toPathExpression

### ISSUE THREAD

**Issue by realgsong** [cyclosproject/ng-swagger-gen#112] opened 2018-10-26 08:10 UTC
/assets/{asset_id} 

toPathExpression return path parameter as it is like /this.rootUrl + `/assets/${asset_id}`,
But parameter variable name is changed to camel case assetId and it causes error of "Cannot find name 'asset_id'

**Comment by luisfpg** [comment] 2018-10-26 11:12
Duplicate of #110.
WIll be fixed shortly.

**Closed by luisfpg** 2018-10-26 11:12 UTC
Labels: bug, duplicate
