### ISSUE TITLE
ng build fails

### ISSUE THREAD

**Issue by Marcus095** [cyclosproject/ng-swagger-gen#89] opened 2018-08-29 19:04 UTC
Hi, 
I currently have an Angular 6 project that has multiple angular libraries, in which there's the generated code with ng-swagger-gen. 

When I try to build the angular library, such as `ng build mylib` it fails because the service contains TypeScript errors:

```
error TS6133: 'HttpParams' is declared but its value is never read.
error TS2322: Type 'null' is not assignable to type 'User[]'.
error TS2322: Type 'Observable<User[] | null>' is not assignable to type 'Observable<User[]>'.
```

Code related to above errors:
```
let _body: Array<User> = null;
```
```
getUserCollection(page?: number): Observable<Array<User>> {
    return this.getUserCollectionResponse(page).pipe(
      map(_r => _r.body)
    );
  }
```

Is this a known issue that will be fixed? Otherwise, since the code itself works, is it possible to ignore the linting on the generated code during the build process? I still need the code in the build, so ignoring it completely won't work.

If you need more details let me know

**Comment by luisfpg** [comment] 2018-09-10 03:36
Can you share the swagger source, and the generated getUserCollectionResponse method?

**Comment by Marcus095** [comment] 2018-09-10 08:19
Sure thing @luisfpg , here's the source:

```
{
  "swagger": "2.0",
  "basePath": "\/user",
  "info": {
    "title": "users",
    "version": "1.0.0",
    "description": "Manage users"
  },
  "paths": {
    "\/api\/user\/": {
      "post": {
        "tags": ["User"],
        "operationId": "postUserCollection",
        "consumes": ["application\/json", "text\/html"],
        "produces": ["application\/json", "text\/html"],
        "summary": "Creates a User resource.",
        "parameters": [{
          "name": "user",
          "in": "body",
          "description": "The new User resource",
          "schema": {
            "$ref": "#\/definitions\/User"
          }
        }],
        "responses": {
          "201": {
            "description": "User resource created",
            "schema": {
              "$ref": "#\/definitions\/User"
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Resource not found"
          }
        }
      }
    },
    "\/api\/user\/{id}": {
      "get": {
        "tags": ["User"],
        "operationId": "getUserItem",
        "produces": ["application\/json", "text\/html"],
        "summary": "Retrieves a User resource.",
        "parameters": [{
          "name": "id",
          "in": "path",
          "required": true,
          "type": "string"
        }],
        "responses": {
          "200": {
            "description": "User resource response",
            "schema": {
              "$ref": "#\/definitions\/User"
            }
          },
          "404": {
            "description": "Resource not found"
          }
        }
      },
      "put": {
        "tags": ["User"],
        "operationId": "putUserItem",
        "consumes": ["application\/json", "text\/html"],
        "produces": ["application\/json", "text\/html"],
        "summary": "Replaces the User resource.",
        "parameters": [{
          "name": "id",
          "in": "path",
          "type": "string",
          "required": true
        }, {
          "name": "user",
          "in": "body",
          "description": "The updated User resource",
          "schema": {
            "$ref": "#\/definitions\/User"
          }
        }],
        "responses": {
          "200": {
            "description": "User resource updated",
            "schema": {
              "$ref": "#\/definitions\/User"
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Resource not found"
          }
        }
      },
      "delete": {
        "tags": ["User"],
        "operationId": "deleteUserItem",
        "summary": "Removes the User resource.",
        "responses": {
          "204": {
            "description": "User resource deleted"
          },
          "404": {
            "description": "Resource not found"
          }
        },
        "parameters": [{
          "name": "id",
          "in": "path",
          "type": "string",
          "required": true
        }]
      }
    },
    "\/api\/users": {
      "get": {
        "tags": ["User"],
        "operationId": "getUserCollection",
        "produces": ["application\/json", "text\/html"],
        "summary": "Retrieves the collection of User resources.",
        "responses": {
          "200": {
            "description": "User collection response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#\/definitions\/User"
              }
            }
          }
        },
        "parameters": [{
          "name": "page",
          "in": "query",
          "required": false,
          "type": "integer",
          "description": "The collection page number"
        }]
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "description": "A User",
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "lang": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "enabled": {
          "type": "integer"
        },
        "newsletter": {
          "type": "integer"
        },
        "userRoles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "plantGroups": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["gender", "email", "password", "lang", "country"]
    }
  }
}
```


And the getUserCollectionResponse:

```
/**
   * @param page The collection page number
   * @return User collection response
   */
  getUserCollectionResponse(page?: number): Observable<HttpResponse<Array<User>>> {
    let __params = this.newParams();
    let __headers = new HttpHeaders();
    let __body: any = null;
    if (page != null) __params = __params.set('page', page.toString());
    let req = new HttpRequest<any>(
      'GET',
      this.rootUrl + `/api/users`,
      __body,
      {
        headers: __headers,
        params: __params,
        responseType: 'json'
      });

    return this.http.request<any>(req).pipe(
      filter(_r => _r instanceof HttpResponse),
      map(_r => {
        let _resp = _r as HttpResponse<any>;
        let _body: Array<User> = null;
        _body = _resp.body as Array<User>;
        return _resp.clone({body: _body}) as HttpResponse<Array<User>>;
      })
    );
  }
```

**Comment by luisfpg** [comment] 2018-09-14 11:37
Are you using `"strictNullChecks": true` on typescript definitions?
If so, this is a duplicate of #88

**Closed** 2018-09-14 14:36 UTC
